version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip

  build:
    commands:
      - echo "Packaging index-photos Lambda..."
      - cd index-photos
      - if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - zip -r ../index-photos.zip .
      - cd ..

      - echo "Packaging search-photos Lambda..."
      - cd search-photos
      - if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - zip -r ../search-photos.zip .
      - cd ..

  post_build:
    commands:
      - echo "Deploying search-photos Lambda..."
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search-photos.zip
      - echo "Deploying index-photos Lambda..."
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index-photos.zip

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
